name: ScoreboardAPI
version: ${project.version}
main: club.rigox.scoreboard.ScoreboardAPI
api-version: 1.16
authors: [ sebastn_chan ]
description: Scoreboard System of Rigox Club.
website: https://rigox.club
depend:
  - PlaceholderAPI
  - LuckPerms
softdepend:
  - CMI
  - CMIEInjector