general:
  title: "&c&lRigox &7| &fVanilla"
  body:
    - ""
    - "&fNombre: &b%player_name%"
    - ""
    - "&fRango: &e%luckperms_primary_group_name%"
    - "&fCréditos: &e%vault_eco_balance_formatted%"
    - ""
    - "&fVoteParty: &a6&7/30" # TODO
    - ""
    - "&crigox.club"

staff-mode:
  title: "&c&lRigox &7| &fStaff Mode"
  body:
    - ""
    - "&fPlayer: &b%player_name%"
    - ""
    - "Vanish: &e%vanillacore_vanished%"
    - ""
    - "&crigox.club"


freeze:
  title: "&c&lRigox &7| &fFrozed"
  body:
    - ""
    - "&eReview the chat!"
    - ""
    - "&7Please don't disconnect"
    - "&7from the server until a"
    - "&7staff screenshared you."
    - ""
    - "&crigox.club"